fiz = Business.find_by(name: "Fizgerald Pub")
sushi = Business.find_by(name: "Sushi Ryusei")
handy = Business.find_by(name: "Handy")
holy = Business.find_by(name: "Holy Ground")
rooftop = Business.find_by(name: "Rooftop 93")
yiwan = Business.find_by(name: "YiWan home services")
richair = Business.find_by(name: "Richair home solutions")
alba = Business.find_by(name: "Alba dry cleaning")
auto = Business.find_by(name: "Autocraft NYC")
hard = Business.find_by(name: "Hard Turn")
ume = Business.find_by(name: "Ume Cosme")
rabbit = Business.find_by(name: "Red Rabbit Club")
playboy = Business.find_by(name: "Playboy Club NYC")
ascent = Business.find_by(name: "Ascent Lounge")
amelie = Business.find_by(name: "Amelie")
ipanema = Business.find_by(name: "Ipanema Restaurant")
tonchin = Business.find_by(name: "TONCHIN NEW YORK")
painter = Business.find_by(name: "212-PAINTER")
aspiro = Business.find_by(name: "Aspiro Renovations")
j = Business.find_by(name: "Little J Cleaners")
sammy = Business.find_by(name: "Sammy Dry Cleaners & Tailor")
prestige = Business.find_by(name: "Prestige Automotive")
manhattan = Business.find_by(name: "Manhattan Automotive")
ian = Business.find_by(name: "Ian Rios New York")
alter = Business.find_by(name: "Alter")
city = Business.find_by(name: "City Glow")
birch = Business.find_by(name: "Birchbox Soho")


user1 = User.find_by(email: "3948794@gmail.com")
user2 = User.find_by(email: "39eru@gmail.com")
user3 = User.find_by(email: "094ui@gmail.com")
user4 = User.find_by(email: "ifj9rew@gmail.com")
user5 = User.find_by(email: "3498tu3w@gmail.com")
user6 = User.find_by(email: "903rhitr@gmail.com")
user7 = User.find_by(email: "fio2u28@gmail.com")
user8 = User.find_by(email: "79iru98@gmail.com")


fiz1 = Upload.create(user_id: user1.id, business_id: fiz.id)
fiz2 = Upload.create(user_id: user3.id, business_id: fiz.id)
fiz3 = Upload.create(user_id: user5.id, business_id: fiz.id)
fiz4 = Upload.create(user_id: user7.id, business_id: fiz.id)
fiz1.photo.attach(io: File.open("./app/assets/images/fiz1.jpg"), filename:"fiz1.jpg")
fiz2.photo.attach(io: File.open("./app/assets/images/fiz2.jpg"), filename:"fiz2.jpg")
fiz3.photo.attach(io: File.open("./app/assets/images/fiz3.jpg"), filename:"fiz3.jpg")
fiz4.photo.attach(io: File.open("./app/assets/images/fiz4.jpg"), filename:"fiz4.jpg")

sushi1 = Upload.create(user_id: user3.id, business_id: sushi.id)
sushi2 = Upload.create(user_id: user2.id, business_id: sushi.id)
sushi3 = Upload.create(user_id: user4.id, business_id: sushi.id)
sushi4 = Upload.create(user_id: user8.id, business_id: sushi.id)
sushi1.photo.attach(io: File.open("./app/assets/images/sushi1.jpg"), filename:"sushi1.jpg")
sushi2.photo.attach(io: File.open("./app/assets/images/sushi2.jpg"), filename:"sushi2.jpg")
sushi3.photo.attach(io: File.open("./app/assets/images/sushi3.jpg"), filename:"sushi3.jpg")
sushi4.photo.attach(io: File.open("./app/assets/images/sushi4.jpg"), filename:"sushi4.jpg")

handy1 = Upload.create(user_id: user1.id, business_id: handy.id)
handy2 = Upload.create(user_id: user7.id, business_id: handy.id)
handy3 = Upload.create(user_id: user2.id, business_id: handy.id)
handy4 = Upload.create(user_id: user8.id, business_id: handy.id)
handy1.photo.attach(io: File.open("./app/assets/images/handy1.jpg"), filename:"handy1.jpg")
handy2.photo.attach(io: File.open("./app/assets/images/handy2.jpg"), filename:"handy2.jpg")
handy3.photo.attach(io: File.open("./app/assets/images/handy3.jpg"), filename:"handy3.jpg")
handy4.photo.attach(io: File.open("./app/assets/images/handy4.jpg"), filename:"handy4.jpg")

holy1 = Upload.create(user_id: user3.id, business_id: holy.id)
holy2 = Upload.create(user_id: user2.id, business_id: holy.id)
holy3 = Upload.create(user_id: user4.id, business_id: holy.id)
holy4 = Upload.create(user_id: user5.id, business_id: holy.id)
holy1.photo.attach(io: File.open("./app/assets/images/holy1.jpg"), filename:"holy1.jpg")
holy2.photo.attach(io: File.open("./app/assets/images/holy2.jpg"), filename:"holy2.jpg")
holy3.photo.attach(io: File.open("./app/assets/images/holy3.jpg"), filename:"holy3.jpg")
holy4.photo.attach(io: File.open("./app/assets/images/holy4.jpg"), filename:"holy4.jpg")

rooftop1 = Upload.create(user_id: user3.id, business_id: rooftop.id)
rooftop2 = Upload.create(user_id: user2.id, business_id: rooftop.id)
rooftop3 = Upload.create(user_id: user4.id, business_id: rooftop.id)
rooftop4 = Upload.create(user_id: user5.id, business_id: rooftop.id)
rooftop1.photo.attach(io: File.open("./app/assets/images/rooftop1.jpg"), filename:"rooftop1.jpg")
rooftop2.photo.attach(io: File.open("./app/assets/images/rooftop2.jpg"), filename:"rooftop2.jpg")
rooftop3.photo.attach(io: File.open("./app/assets/images/rooftop3.jpg"), filename:"rooftop3.jpg")
rooftop4.photo.attach(io: File.open("./app/assets/images/rooftop4.jpg"), filename:"rooftop4.jpg")

yiwan1 = Upload.create(user_id: user3.id, business_id: yiwan.id)
yiwan2 = Upload.create(user_id: user6.id, business_id: yiwan.id)
yiwan3 = Upload.create(user_id: user4.id, business_id: yiwan.id)
yiwan4 = Upload.create(user_id: user5.id, business_id: yiwan.id)
yiwan1.photo.attach(io: File.open("./app/assets/images/yiwan1.jpg"), filename:"yiwan1.jpg")
yiwan2.photo.attach(io: File.open("./app/assets/images/yiwan2.jpg"), filename:"yiwan2.jpg")
yiwan3.photo.attach(io: File.open("./app/assets/images/yiwan3.jpg"), filename:"yiwan3.jpg")
yiwan4.photo.attach(io: File.open("./app/assets/images/yiwan4.jpg"), filename:"yiwan4.jpg")

richair1 = Upload.create(user_id: user3.id, business_id: richair.id)
richair2 = Upload.create(user_id: user6.id, business_id: richair.id)
richair3 = Upload.create(user_id: user2.id, business_id: richair.id)
richair4 = Upload.create(user_id: user1.id, business_id: richair.id)
richair1.photo.attach(io: File.open("./app/assets/images/richair1.jpg"), filename:"richair1.jpg")
richair2.photo.attach(io: File.open("./app/assets/images/richair2.jpg"), filename:"richair2.jpg")
richair3.photo.attach(io: File.open("./app/assets/images/richair3.jpg"), filename:"richair3.jpg")
richair4.photo.attach(io: File.open("./app/assets/images/richair4.jpg"), filename:"richair4.jpg")

alba1 = Upload.create(user_id: user3.id, business_id: alba.id)
alba2 = Upload.create(user_id: user7.id, business_id: alba.id)
alba3 = Upload.create(user_id: user2.id, business_id: alba.id)
alba4 = Upload.create(user_id: user1.id, business_id: alba.id)
alba1.photo.attach(io: File.open("./app/assets/images/alba1.jpg"), filename:"alba1.jpg")
alba2.photo.attach(io: File.open("./app/assets/images/alba2.jpg"), filename:"alba2.jpg")
alba3.photo.attach(io: File.open("./app/assets/images/alba3.jpg"), filename:"alba3.jpg")
alba4.photo.attach(io: File.open("./app/assets/images/alba4.jpg"), filename:"alba4.jpg")

auto1 = Upload.create(user_id: user8.id, business_id: auto.id)
auto2 = Upload.create(user_id: user7.id, business_id: auto.id)
auto3 = Upload.create(user_id: user2.id, business_id: auto.id)
auto4 = Upload.create(user_id: user1.id, business_id: auto.id)
auto1.photo.attach(io: File.open("./app/assets/images/auto1.jpg"), filename:"auto1.jpg")
auto2.photo.attach(io: File.open("./app/assets/images/auto2.jpg"), filename:"auto2.jpg")
auto3.photo.attach(io: File.open("./app/assets/images/auto3.jpg"), filename:"auto3.jpg")
auto4.photo.attach(io: File.open("./app/assets/images/auto4.jpg"), filename:"auto4.jpg")

hard1 = Upload.create(user_id: user8.id, business_id: hard.id)
hard2 = Upload.create(user_id: user7.id, business_id: hard.id)
hard3 = Upload.create(user_id: user2.id, business_id: hard.id)
hard4 = Upload.create(user_id: user5.id, business_id: hard.id)
hard1.photo.attach(io: File.open("./app/assets/images/hard1.jpg"), filename:"hard1.jpg")
hard2.photo.attach(io: File.open("./app/assets/images/hard2.jpg"), filename:"hard2.jpg")
hard3.photo.attach(io: File.open("./app/assets/images/hard3.jpg"), filename:"hard3.jpg")
hard4.photo.attach(io: File.open("./app/assets/images/hard4.jpg"), filename:"hard4.jpg")

ume1 = Upload.create(user_id: user4.id, business_id: ume.id)
ume2 = Upload.create(user_id: user7.id, business_id: ume.id)
ume3 = Upload.create(user_id: user2.id, business_id: ume.id)
ume4 = Upload.create(user_id: user5.id, business_id: ume.id)
ume1.photo.attach(io: File.open("./app/assets/images/ume1.jpg"), filename:"ume1.jpg")
ume2.photo.attach(io: File.open("./app/assets/images/ume2.jpg"), filename:"ume2.jpg")
ume3.photo.attach(io: File.open("./app/assets/images/ume3.jpg"), filename:"ume3.jpg")
ume4.photo.attach(io: File.open("./app/assets/images/ume4.jpg"), filename:"ume4.jpg")

rabbit1 = Upload.create(user_id: user4.id, business_id: rabbit.id)
rabbit2 = Upload.create(user_id: user7.id, business_id: rabbit.id)
rabbit3 = Upload.create(user_id: user8.id, business_id: rabbit.id)
rabbit4 = Upload.create(user_id: user5.id, business_id: rabbit.id)
rabbit1.photo.attach(io: File.open("./app/assets/images/rabbit1.jpg"), filename:"rabbit1.jpg")
rabbit2.photo.attach(io: File.open("./app/assets/images/rabbit2.jpg"), filename:"rabbit2.jpg")
rabbit3.photo.attach(io: File.open("./app/assets/images/rabbit3.jpg"), filename:"rabbit3.jpg")
rabbit4.photo.attach(io: File.open("./app/assets/images/rabbit4.jpg"), filename:"rabbit4.jpg")

playboy1 = Upload.create(user_id: user4.id, business_id: playboy.id)
playboy2 = Upload.create(user_id: user7.id, business_id: playboy.id)
playboy3 = Upload.create(user_id: user8.id, business_id: playboy.id)
playboy4 = Upload.create(user_id: user2.id, business_id: playboy.id)
playboy1.photo.attach(io: File.open("./app/assets/images/playboy1.jpg"), filename:"playboy1.jpg")
playboy2.photo.attach(io: File.open("./app/assets/images/playboy2.jpg"), filename:"playboy2.jpg")
playboy3.photo.attach(io: File.open("./app/assets/images/playboy3.jpg"), filename:"playboy3.jpg")
playboy4.photo.attach(io: File.open("./app/assets/images/playboy4.jpg"), filename:"playboy4.jpg")

ascent1 = Upload.create(user_id: user4.id, business_id: ascent.id)
ascent2 = Upload.create(user_id: user1.id, business_id: ascent.id)
ascent3 = Upload.create(user_id: user8.id, business_id: ascent.id)
ascent4 = Upload.create(user_id: user2.id, business_id: ascent.id)
ascent1.photo.attach(io: File.open("./app/assets/images/ascent1.jpg"), filename:"ascent1.jpg")
ascent2.photo.attach(io: File.open("./app/assets/images/ascent2.jpg"), filename:"ascent2.jpg")
ascent3.photo.attach(io: File.open("./app/assets/images/ascent3.jpg"), filename:"ascent3.jpg")
ascent4.photo.attach(io: File.open("./app/assets/images/ascent4.jpg"), filename:"ascent4.jpg")

amelie1 = Upload.create(user_id: user4.id, business_id: amelie.id)
amelie2 = Upload.create(user_id: user1.id, business_id: amelie.id)
amelie3 = Upload.create(user_id: user6.id, business_id: amelie.id)
amelie4 = Upload.create(user_id: user2.id, business_id: amelie.id)
amelie1.photo.attach(io: File.open("./app/assets/images/amelie1.jpg"), filename:"amelie1.jpg")
amelie2.photo.attach(io: File.open("./app/assets/images/amelie2.jpg"), filename:"amelie2.jpg")
amelie3.photo.attach(io: File.open("./app/assets/images/amelie3.jpg"), filename:"amelie3.jpg")
amelie4.photo.attach(io: File.open("./app/assets/images/amelie4.jpg"), filename:"amelie4.jpg")

ipanema1 = Upload.create(user_id: user4.id, business_id: ipanema.id)
ipanema2 = Upload.create(user_id: user5.id, business_id: ipanema.id)
ipanema3 = Upload.create(user_id: user6.id, business_id: ipanema.id)
ipanema4 = Upload.create(user_id: user2.id, business_id: ipanema.id)
ipanema1.photo.attach(io: File.open("./app/assets/images/ipanema1.jpg"), filename:"ipanema1.jpg")
ipanema2.photo.attach(io: File.open("./app/assets/images/ipanema2.jpg"), filename:"ipanema2.jpg")
ipanema3.photo.attach(io: File.open("./app/assets/images/ipanema3.jpg"), filename:"ipanema3.jpg")
ipanema4.photo.attach(io: File.open("./app/assets/images/ipanema4.jpg"), filename:"ipanema4.jpg")


tonchin1 = Upload.create(user_id: user8.id, business_id: tonchin.id)
tonchin2 = Upload.create(user_id: user5.id, business_id: tonchin.id)
tonchin3 = Upload.create(user_id: user6.id, business_id: tonchin.id)
tonchin4 = Upload.create(user_id: user2.id, business_id: tonchin.id)
tonchin1.photo.attach(io: File.open("./app/assets/images/tonchin1.jpg"), filename:"tonchin1.jpg")
tonchin2.photo.attach(io: File.open("./app/assets/images/tonchin2.jpg"), filename:"tonchin2.jpg")
tonchin3.photo.attach(io: File.open("./app/assets/images/tonchin3.jpg"), filename:"tonchin3.jpg")
tonchin4.photo.attach(io: File.open("./app/assets/images/tonchin4.jpg"), filename:"tonchin4.jpg")

painter1 = Upload.create(user_id: user8.id, business_id: painter.id)
painter2 = Upload.create(user_id: user5.id, business_id: painter.id)
painter3 = Upload.create(user_id: user6.id, business_id: painter.id)
painter4 = Upload.create(user_id: user1.id, business_id: painter.id)
painter1.photo.attach(io: File.open("./app/assets/images/painter1.jpg"), filename:"painter1.jpg")
painter2.photo.attach(io: File.open("./app/assets/images/painter2.jpg"), filename:"painter2.jpg")
painter3.photo.attach(io: File.open("./app/assets/images/painter3.jpg"), filename:"painter3.jpg")
painter4.photo.attach(io: File.open("./app/assets/images/painter4.jpg"), filename:"painter4.jpg")

aspiro1 = Upload.create(user_id: user8.id, business_id: aspiro.id)
aspiro2 = Upload.create(user_id: user5.id, business_id: aspiro.id)
aspiro3 = Upload.create(user_id: user6.id, business_id: aspiro.id)
aspiro4 = Upload.create(user_id: user1.id, business_id: aspiro.id)
aspiro1.photo.attach(io: File.open("./app/assets/images/aspiro1.jpg"), filename:"aspiro1.jpg")
aspiro2.photo.attach(io: File.open("./app/assets/images/aspiro2.jpg"), filename:"aspiro2.jpg")
aspiro3.photo.attach(io: File.open("./app/assets/images/aspiro3.jpg"), filename:"aspiro3.jpg")
aspiro4.photo.attach(io: File.open("./app/assets/images/aspiro4.jpg"), filename:"aspiro4.jpg")

j1 = Upload.create(user_id: user8.id, business_id: j.id)
j2 = Upload.create(user_id: user5.id, business_id: j.id)
j3 = Upload.create(user_id: user6.id, business_id: j.id)
j4 = Upload.create(user_id: user4.id, business_id: j.id)
j1.photo.attach(io: File.open("./app/assets/images/j1.jpg"), filename:"j1.jpg")
j2.photo.attach(io: File.open("./app/assets/images/j2.jpg"), filename:"j2.jpg")
j3.photo.attach(io: File.open("./app/assets/images/j3.jpg"), filename:"j3.jpg")
j4.photo.attach(io: File.open("./app/assets/images/j4.jpg"), filename:"j4.jpg")

sammy1 = Upload.create(user_id: user8.id, business_id: sammy.id)
sammy2 = Upload.create(user_id: user5.id, business_id: sammy.id)
sammy3 = Upload.create(user_id: user6.id, business_id: sammy.id)
sammy4 = Upload.create(user_id: user4.id, business_id: sammy.id)
sammy1.photo.attach(io: File.open("./app/assets/images/sammy1.jpg"), filename:"sammy1.jpg")
sammy2.photo.attach(io: File.open("./app/assets/images/sammy2.jpg"), filename:"sammy2.jpg")
sammy3.photo.attach(io: File.open("./app/assets/images/sammy3.jpg"), filename:"sammy3.jpg")
sammy4.photo.attach(io: File.open("./app/assets/images/sammy4.jpg"), filename:"sammy4.jpg")

prestige1 = Upload.create(user_id: user8.id, business_id: prestige.id)
prestige2 = Upload.create(user_id: user5.id, business_id: prestige.id)
prestige3 = Upload.create(user_id: user1.id, business_id: prestige.id)
prestige4 = Upload.create(user_id: user4.id, business_id: prestige.id)
prestige1.photo.attach(io: File.open("./app/assets/images/prestige1.jpg"), filename:"prestige1.jpg")
prestige2.photo.attach(io: File.open("./app/assets/images/prestige2.jpg"), filename:"prestige2.jpg")
prestige3.photo.attach(io: File.open("./app/assets/images/prestige3.jpg"), filename:"prestige3.jpg")
prestige4.photo.attach(io: File.open("./app/assets/images/prestige4.jpg"), filename:"prestige4.jpg")


manhattan1 = Upload.create(user_id: user8.id, business_id: manhattan.id)
manhattan2 = Upload.create(user_id: user5.id, business_id: manhattan.id)
manhattan3 = Upload.create(user_id: user1.id, business_id: manhattan.id)
manhattan4 = Upload.create(user_id: user3.id, business_id: manhattan.id)
manhattan1.photo.attach(io: File.open("./app/assets/images/manhattan1.jpg"), filename:"manhattan1.jpg")
manhattan2.photo.attach(io: File.open("./app/assets/images/manhattan2.jpg"), filename:"manhattan2.jpg")
manhattan3.photo.attach(io: File.open("./app/assets/images/manhattan3.jpg"), filename:"manhattan3.jpg")
manhattan4.photo.attach(io: File.open("./app/assets/images/manhattan4.jpg"), filename:"manhattan4.jpg")

ian1 = Upload.create(user_id: user8.id, business_id: ian.id)
ian2 = Upload.create(user_id: user4.id, business_id: ian.id)
ian3 = Upload.create(user_id: user1.id, business_id: ian.id)
ian4 = Upload.create(user_id: user3.id, business_id: ian.id)
ian1.photo.attach(io: File.open("./app/assets/images/ian1.jpg"), filename:"ian1.jpg")
ian2.photo.attach(io: File.open("./app/assets/images/ian2.jpg"), filename:"ian2.jpg")
ian3.photo.attach(io: File.open("./app/assets/images/ian3.jpg"), filename:"ian3.jpg")
ian4.photo.attach(io: File.open("./app/assets/images/ian4.jpg"), filename:"ian4.jpg")

alter1 = Upload.create(user_id: user5.id, business_id: alter.id)
alter2 = Upload.create(user_id: user4.id, business_id: alter.id)
alter3 = Upload.create(user_id: user1.id, business_id: alter.id)
alter4 = Upload.create(user_id: user3.id, business_id: alter.id)
alter1.photo.attach(io: File.open("./app/assets/images/alter1.jpg"), filename:"alter1.jpg")
alter2.photo.attach(io: File.open("./app/assets/images/alter2.jpg"), filename:"alter2.jpg")
alter3.photo.attach(io: File.open("./app/assets/images/alter3.jpg"), filename:"alter3.jpg")
alter4.photo.attach(io: File.open("./app/assets/images/alter4.jpg"), filename:"alter4.jpg")

city1 = Upload.create(user_id: user5.id, business_id: city.id)
city2 = Upload.create(user_id: user4.id, business_id: city.id)
city3 = Upload.create(user_id: user1.id, business_id: city.id)
city4 = Upload.create(user_id: user3.id, business_id: city.id)
city1.photo.attach(io: File.open("./app/assets/images/city1.jpg"), filename:"city1.jpg")
city2.photo.attach(io: File.open("./app/assets/images/city2.jpg"), filename:"city2.jpg")
city3.photo.attach(io: File.open("./app/assets/images/city3.jpg"), filename:"city3.jpg")
city4.photo.attach(io: File.open("./app/assets/images/city4.jpg"), filename:"city4.jpg")

birch1 = Upload.create(user_id: user5.id, business_id: birch.id)
birch2 = Upload.create(user_id: user4.id, business_id: birch.id)
birch3 = Upload.create(user_id: user1.id, business_id: birch.id)
birch4 = Upload.create(user_id: user2.id, business_id: birch.id)
birch1.photo.attach(io: File.open("./app/assets/images/birch1.jpg"), filename:"birch1.jpg")
birch2.photo.attach(io: File.open("./app/assets/images/birch2.jpg"), filename:"birch2.jpg")
birch3.photo.attach(io: File.open("./app/assets/images/birch3.jpg"), filename:"birch3.jpg")
birch4.photo.attach(io: File.open("./app/assets/images/birch4.jpg"), filename:"birch4.jpg")
